export const projectPortfolioData = [
  {
    id: 1,
    title: "Expenses Tracker",
    resources: ["0", "0", "0"],
    description: "Number 11",
    src: {
      light: "/expenses-tracker-1.svg",
      dark: "/expenses-tracker-1-dark.PNG",
    },
    displayDarkModeToggle: "displayDarkModeToggle",
    href: "https://expenses-tracker-je.netlify.app/",
  },
  {
    id: 2,
    title: "Text To Markdown",
    resources: ["1", "1", "1"],
    description: "Number 22",
    src: "/expenses-tracker-2.png",
    darkMode: "",
    href: "",
  },
  {
    id: 3,
    title: "Meme Generator",
    resources: ["2", "2", "2"],
    description: "Number 33",
    src: "/expenses-tracker-3.png",
    darkMode: "",
    href: "",
  },
  {
    id: 4,
    title: "Tenzies Game",
    resources: ["3", "3", "3"],
    description: "",
    src: "/expenses-tracker-4.png",
    description: "Number 44",
    href: "",
  },
];
